In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
matches = pd.read_csv("/content/sample_data/matches.csv")
data_m = matches.copy()

In [3]:
data_m.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [ ]:
data_m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [ ]:
data_m[data_m['city'].isna()]

Empty DataFrame
Columns: [id, season, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2]
Index: []

In [5]:
data_m['season'].value_counts()

season
2013       76
2022       74
2012       74
2023       74
2011       73
2024       71
2019       60
2016       60
2009/10    60
2021       60
2020/21    60
2014       60
2018       60
2017       59
2015       59
2007/08    58
2009       57
Name: count, dtype: int64

In [ ]:
data.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [6]:
deliveries = pd.read_csv("/content/sample_data/deliveries.csv")
data = deliveries.copy()

In [7]:
data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [20]:
data['match_id'].value_counts()

match_id
1216517    269
392190     267
1426268    265
1082625    263
729315     262
          ...
392183     108
829807     106
598068     100
501265      63
1178424     51
Name: count, Length: 1095, dtype: int64

In [16]:
data[data['match_id'] == 1216517]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
185115,1216517,1,Mumbai Indians,Kings XI Punjab,0,1,RG Sharma,GJ Maxwell,Q de Kock,1,0,1,NaN,0,NaN,NaN,NaN
185116,1216517,1,Mumbai Indians,Kings XI Punjab,0,2,Q de Kock,GJ Maxwell,RG Sharma,0,0,0,NaN,0,NaN,NaN,NaN
185117,1216517,1,Mumbai Indians,Kings XI Punjab,0,3,Q de Kock,GJ Maxwell,RG Sharma,1,0,1,NaN,0,NaN,NaN,NaN
185118,1216517,1,Mumbai Indians,Kings XI Punjab,0,4,RG Sharma,GJ Maxwell,Q de Kock,0,0,0,NaN,0,NaN,NaN,NaN
185119,1216517,1,Mumbai Indians,Kings XI Punjab,0,5,RG Sharma,GJ Maxwell,Q de Kock,4,0,4,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185379,1216517,5,Mumbai Indians,Kings XI Punjab,0,8,KA Pollard,CJ Jordan,SA Yadav,2,0,2,NaN,0,NaN,NaN,NaN
185380,1216517,6,Kings XI Punjab,Mumbai Indians,0,1,CH Gayle,TA Boult,MA Agarwal,6,0,6,NaN,0,NaN,NaN,NaN
185381,1216517,6,Kings XI Punjab,Mumbai Indians,0,2,CH Gayle,TA Boult,MA Agarwal,1,0,1,NaN,0,NaN,NaN,NaN
185382,1216517,6,Kings XI Punjab,Mumbai Indians,0,3,MA Agarwal,TA Boult,CH Gayle,4,0,4,NaN,0,NaN,NaN,NaN
185383,1216517,6,Kings XI Punjab,Mumbai Indians,0,4,MA Agarwal,TA Boult,CH Gayle,4,0,4,NaN,0,NaN,NaN,NaN

In [17]:
data_m[data_m['id'] == 1216517]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
791,1216517,2020/21,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel

In [21]:
data[(data['match_id'] == 1216517) & (data['extra_runs'] > 0)]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
185128,1216517,1,Mumbai Indians,Kings XI Punjab,2,2,Q de Kock,Arshdeep Singh,RG Sharma,0,1,1,wides,0,NaN,NaN,NaN
185133,1216517,1,Mumbai Indians,Kings XI Punjab,2,7,SA Yadav,Arshdeep Singh,Q de Kock,0,1,1,legbyes,0,NaN,NaN,NaN
185178,1216517,1,Mumbai Indians,Kings XI Punjab,10,3,KH Pandya,DJ Hooda,Q de Kock,0,1,1,legbyes,0,NaN,NaN,NaN
185191,1216517,1,Mumbai Indians,Kings XI Punjab,12,4,Q de Kock,M Ashwin,KH Pandya,0,4,4,byes,0,NaN,NaN,NaN
185253,1216517,2,Kings XI Punjab,Mumbai Indians,2,6,KL Rahul,TA Boult,MA Agarwal,0,1,1,wides,0,NaN,NaN,NaN
185275,1216517,2,Kings XI Punjab,Mumbai Indians,6,3,CH Gayle,KA Pollard,KL Rahul,0,1,1,wides,0,NaN,NaN,NaN
185278,1216517,2,Kings XI Punjab,Mumbai Indians,6,6,CH Gayle,KA Pollard,KL Rahul,0,1,1,wides,0,NaN,NaN,NaN
185331,1216517,2,Kings XI Punjab,Mumbai Indians,15,3,KL Rahul,JJ Bumrah,DJ Hooda,0,1,1,wides,0,NaN,NaN,NaN
185373,1216517,5,Mumbai Indians,Kings XI Punjab,0,2,HH Pandya,CJ Jordan,KA Pollard,0,1,1,wides,0,NaN,NaN,NaN
185376,1216517,5,Mumbai Indians,Kings XI Punjab,0,5,KA Pollard,CJ Jordan,HH Pandya,0,1,1,wides,0,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [ ]:
data.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [ ]:
data_m.loc[(data_m['venue'] == 'Dubai International Cricket Stadium') & (data_m['city'].isna()), 'city'] = 'Dubai'

In [ ]:
data_m.loc[(data_m['venue'] == 'Sharjah Cricket Stadium') & (data_m['city'].isna()), 'city'] = 'Sharjah'

In [35]:
super_over_matches = data_m[data_m['super_over'] == 'Y']

teams = pd.concat([super_over_matches['team1'], super_over_matches['team2']])

team_counts = teams.value_counts()

print(team_counts)

Kolkata Knight Riders          4
Sunrisers Hyderabad            4
Kings XI Punjab                4
Mumbai Indians                 4
Delhi Capitals                 3
Royal Challengers Bangalore    3
Rajasthan Royals               3
Chennai Super Kings            1
Gujarat Lions                  1
Delhi Daredevils               1
Name: count, dtype: int64

In [37]:
data_m['player_of_match'].value_counts().head(25)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         19
V Kohli           18
DA Warner         18
MS Dhoni          17
YK Pathan         16
RA Jadeja         16
SR Watson         16
AD Russell        15
SP Narine         15
SK Raina          14
KA Pollard        14
AM Rahane         13
JC Buttler        13
KL Rahul          13
G Gambhir         13
A Mishra          12
S Dhawan          12
MEK Hussey        12
Rashid Khan       12
V Sehwag          11
DR Smith          11
RD Gaikwad        11
SV Samson         11
Name: count, dtype: int64